---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 178.154.201.193
      ansible_user: centos

vector:
  hosts:    
    vector-01:
      ansible_host: 178.154.205.21
      ansible_user: centos

lighthouse:
  hosts:    
    lighthouse-01:
      ansible_host: 130.193.48.4
      ansible_user: centos