---
- block:
  - name: Install Vector
    become: true
    ansible.builtin.yum:
      name: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm
      state: present
    notify: Restart Vector

  - name: Configure Vector | ensure what directory exists
    become: true
    file:
      path: "{{ vector_config_dir }}"
      state: directory
      mode: 0644

  - name: Configure Vector | Template config
    become: true
    ansible.builtin.template:
      src: vector.yml.j2
      mode: 0644
      dest: "{{ vector_config_dir }}/vector.yml"
  
  - name: Configure Service
    become: true
    ansible.builtin.template:
      src: vector.service.j2
      mode: 0644
      dest: /etc/systemd/system/vector.service
    notify: Restart Vector
