---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
   
- name: Install Vector
  hosts: vector
  roles:
    - vector-role
    
- name: Install nginx and Lighthouse
  hosts: lighthouse
  roles:
    - nginx-role

- name: Install Lighthouse
  hosts: lighthouse
  pre_tasks:
    - name: Lighthouse | Install dependencies
      become: true
      ansible.builtin.yum:
        name: git
        state: present
  roles:
    -lighthouse-role
  